#!/usr/bin/env bash
mv ../../build/html/1.html ../../build/html/001-bulbasaur.html 2>/dev/null
mv ../../build/png/1.png ../../build/png/001-bulbasaur.png 2>/dev/null
mv ../../build/txt/1.txt ../../build/txt/001-bulbasaur.txt 2>/dev/null
mv ../../build/html/2.html ../../build/html/002-ivysaur.html 2>/dev/null
mv ../../build/png/2.png ../../build/png/002-ivysaur.png 2>/dev/null
mv ../../build/txt/2.txt ../../build/txt/002-ivysaur.txt 2>/dev/null
mv ../../build/html/3.html ../../build/html/003-venusaur.html 2>/dev/null
mv ../../build/png/3.png ../../build/png/003-venusaur.png 2>/dev/null
mv ../../build/txt/3.txt ../../build/txt/003-venusaur.txt 2>/dev/null
mv ../../build/html/4.html ../../build/html/004-charmander.html 2>/dev/null
mv ../../build/png/4.png ../../build/png/004-charmander.png 2>/dev/null
mv ../../build/txt/4.txt ../../build/txt/004-charmander.txt 2>/dev/null
mv ../../build/html/5.html ../../build/html/005-charmeleon.html 2>/dev/null
mv ../../build/png/5.png ../../build/png/005-charmeleon.png 2>/dev/null
mv ../../build/txt/5.txt ../../build/txt/005-charmeleon.txt 2>/dev/null
mv ../../build/html/6.html ../../build/html/006-charizard.html 2>/dev/null
mv ../../build/png/6.png ../../build/png/006-charizard.png 2>/dev/null
mv ../../build/txt/6.txt ../../build/txt/006-charizard.txt 2>/dev/null
mv ../../build/html/7.html ../../build/html/007-squirtle.html 2>/dev/null
mv ../../build/png/7.png ../../build/png/007-squirtle.png 2>/dev/null
mv ../../build/txt/7.txt ../../build/txt/007-squirtle.txt 2>/dev/null
mv ../../build/html/8.html ../../build/html/008-wartortle.html 2>/dev/null
mv ../../build/png/8.png ../../build/png/008-wartortle.png 2>/dev/null
mv ../../build/txt/8.txt ../../build/txt/008-wartortle.txt 2>/dev/null
mv ../../build/html/9.html ../../build/html/009-blastoise.html 2>/dev/null
mv ../../build/png/9.png ../../build/png/009-blastoise.png 2>/dev/null
mv ../../build/txt/9.txt ../../build/txt/009-blastoise.txt 2>/dev/null
mv ../../build/html/10.html ../../build/html/010-caterpie.html 2>/dev/null
mv ../../build/png/10.png ../../build/png/010-caterpie.png 2>/dev/null
mv ../../build/txt/10.txt ../../build/txt/010-caterpie.txt 2>/dev/null
mv ../../build/html/11.html ../../build/html/011-metapod.html 2>/dev/null
mv ../../build/png/11.png ../../build/png/011-metapod.png 2>/dev/null
mv ../../build/txt/11.txt ../../build/txt/011-metapod.txt 2>/dev/null
mv ../../build/html/12.html ../../build/html/012-butterfree.html 2>/dev/null
mv ../../build/png/12.png ../../build/png/012-butterfree.png 2>/dev/null
mv ../../build/txt/12.txt ../../build/txt/012-butterfree.txt 2>/dev/null
mv ../../build/html/13.html ../../build/html/013-weedle.html 2>/dev/null
mv ../../build/png/13.png ../../build/png/013-weedle.png 2>/dev/null
mv ../../build/txt/13.txt ../../build/txt/013-weedle.txt 2>/dev/null
mv ../../build/html/14.html ../../build/html/014-kakuna.html 2>/dev/null
mv ../../build/png/14.png ../../build/png/014-kakuna.png 2>/dev/null
mv ../../build/txt/14.txt ../../build/txt/014-kakuna.txt 2>/dev/null
mv ../../build/html/15.html ../../build/html/015-beedrill.html 2>/dev/null
mv ../../build/png/15.png ../../build/png/015-beedrill.png 2>/dev/null
mv ../../build/txt/15.txt ../../build/txt/015-beedrill.txt 2>/dev/null
mv ../../build/html/16.html ../../build/html/016-pidgey.html 2>/dev/null
mv ../../build/png/16.png ../../build/png/016-pidgey.png 2>/dev/null
mv ../../build/txt/16.txt ../../build/txt/016-pidgey.txt 2>/dev/null
mv ../../build/html/17.html ../../build/html/017-pidgeotto.html 2>/dev/null
mv ../../build/png/17.png ../../build/png/017-pidgeotto.png 2>/dev/null
mv ../../build/txt/17.txt ../../build/txt/017-pidgeotto.txt 2>/dev/null
mv ../../build/html/18.html ../../build/html/018-pidgeot.html 2>/dev/null
mv ../../build/png/18.png ../../build/png/018-pidgeot.png 2>/dev/null
mv ../../build/txt/18.txt ../../build/txt/018-pidgeot.txt 2>/dev/null
mv ../../build/html/19.html ../../build/html/019-rattata.html 2>/dev/null
mv ../../build/png/19.png ../../build/png/019-rattata.png 2>/dev/null
mv ../../build/txt/19.txt ../../build/txt/019-rattata.txt 2>/dev/null
mv ../../build/html/20.html ../../build/html/020-raticate.html 2>/dev/null
mv ../../build/png/20.png ../../build/png/020-raticate.png 2>/dev/null
mv ../../build/txt/20.txt ../../build/txt/020-raticate.txt 2>/dev/null
mv ../../build/html/21.html ../../build/html/021-spearow.html 2>/dev/null
mv ../../build/png/21.png ../../build/png/021-spearow.png 2>/dev/null
mv ../../build/txt/21.txt ../../build/txt/021-spearow.txt 2>/dev/null
mv ../../build/html/22.html ../../build/html/022-fearow.html 2>/dev/null
mv ../../build/png/22.png ../../build/png/022-fearow.png 2>/dev/null
mv ../../build/txt/22.txt ../../build/txt/022-fearow.txt 2>/dev/null
mv ../../build/html/23.html ../../build/html/023-ekans.html 2>/dev/null
mv ../../build/png/23.png ../../build/png/023-ekans.png 2>/dev/null
mv ../../build/txt/23.txt ../../build/txt/023-ekans.txt 2>/dev/null
mv ../../build/html/24.html ../../build/html/024-arbok.html 2>/dev/null
mv ../../build/png/24.png ../../build/png/024-arbok.png 2>/dev/null
mv ../../build/txt/24.txt ../../build/txt/024-arbok.txt 2>/dev/null
mv ../../build/html/25.html ../../build/html/025-pikachu.html 2>/dev/null
mv ../../build/png/25.png ../../build/png/025-pikachu.png 2>/dev/null
mv ../../build/txt/25.txt ../../build/txt/025-pikachu.txt 2>/dev/null
mv ../../build/html/26.html ../../build/html/026-raichu.html 2>/dev/null
mv ../../build/png/26.png ../../build/png/026-raichu.png 2>/dev/null
mv ../../build/txt/26.txt ../../build/txt/026-raichu.txt 2>/dev/null
mv ../../build/html/27.html ../../build/html/027-sandshrew.html 2>/dev/null
mv ../../build/png/27.png ../../build/png/027-sandshrew.png 2>/dev/null
mv ../../build/txt/27.txt ../../build/txt/027-sandshrew.txt 2>/dev/null
mv ../../build/html/28.html ../../build/html/028-sandslash.html 2>/dev/null
mv ../../build/png/28.png ../../build/png/028-sandslash.png 2>/dev/null
mv ../../build/txt/28.txt ../../build/txt/028-sandslash.txt 2>/dev/null
mv ../../build/html/29.html ../../build/html/029-nidoran.html 2>/dev/null
mv ../../build/png/29.png ../../build/png/029-nidoran.png 2>/dev/null
mv ../../build/txt/29.txt ../../build/png/029-nidoran.txt 2>/dev/null
mv ../../build/html/30.html ../../build/html/030-nidorina.html 2>/dev/null
mv ../../build/png/30.png ../../build/png/030-nidorina.png 2>/dev/null
mv ../../build/txt/30.txt ../../build/txt/030-nidorina.txt 2>/dev/null
mv ../../build/html/31.html ../../build/html/031-nidoqueen.html 2>/dev/null
mv ../../build/png/31.png ../../build/png/031-nidoqueen.png 2>/dev/null
mv ../../build/txt/31.txt ../../build/txt/031-nidoqueen.txt 2>/dev/null
mv ../../build/html/32.html ../../build/html/032-nidoran.html 2>/dev/null
mv ../../build/png/32.png ../../build/png/032-nidoran.png 2>/dev/null
mv ../../build/txt/32.txt ../../build/png/032-nidoran.txt 2>/dev/null
mv ../../build/html/33.html ../../build/html/033-nidorino.html 2>/dev/null
mv ../../build/png/33.png ../../build/png/033-nidorino.png 2>/dev/null
mv ../../build/txt/33.txt ../../build/txt/033-nidorino.txt 2>/dev/null
mv ../../build/html/34.html ../../build/html/034-nidoking.html 2>/dev/null
mv ../../build/png/34.png ../../build/png/034-nidoking.png 2>/dev/null
mv ../../build/txt/34.txt ../../build/txt/034-nidoking.txt 2>/dev/null
mv ../../build/html/35.html ../../build/html/035-clefairy.html 2>/dev/null
mv ../../build/png/35.png ../../build/png/035-clefairy.png 2>/dev/null
mv ../../build/txt/35.txt ../../build/txt/035-clefairy.txt 2>/dev/null
mv ../../build/html/36.html ../../build/html/036-clefable.html 2>/dev/null
mv ../../build/png/36.png ../../build/png/036-clefable.png 2>/dev/null
mv ../../build/txt/36.txt ../../build/txt/036-clefable.txt 2>/dev/null
mv ../../build/html/37.html ../../build/html/037-vulpix.html 2>/dev/null
mv ../../build/png/37.png ../../build/png/037-vulpix.png 2>/dev/null
mv ../../build/txt/37.txt ../../build/txt/037-vulpix.txt 2>/dev/null
mv ../../build/html/38.html ../../build/html/038-ninetales.html 2>/dev/null
mv ../../build/png/38.png ../../build/png/038-ninetales.png 2>/dev/null
mv ../../build/txt/38.txt ../../build/txt/038-ninetales.txt 2>/dev/null
mv ../../build/html/39.html ../../build/html/039-jigglypuff.html 2>/dev/null
mv ../../build/png/39.png ../../build/png/039-jigglypuff.png 2>/dev/null
mv ../../build/txt/39.txt ../../build/txt/039-jigglypuff.txt 2>/dev/null
mv ../../build/html/40.html ../../build/html/040-wigglytuff.html 2>/dev/null
mv ../../build/png/40.png ../../build/png/040-wigglytuff.png 2>/dev/null
mv ../../build/txt/40.txt ../../build/txt/040-wigglytuff.txt 2>/dev/null
mv ../../build/html/41.html ../../build/html/041-zubat.html 2>/dev/null
mv ../../build/png/41.png ../../build/png/041-zubat.png 2>/dev/null
mv ../../build/txt/41.txt ../../build/txt/041-zubat.txt 2>/dev/null
mv ../../build/html/42.html ../../build/html/042-golbat.html 2>/dev/null
mv ../../build/png/42.png ../../build/png/042-golbat.png 2>/dev/null
mv ../../build/txt/42.txt ../../build/txt/042-golbat.txt 2>/dev/null
mv ../../build/html/43.html ../../build/html/043-oddish.html 2>/dev/null
mv ../../build/png/43.png ../../build/png/043-oddish.png 2>/dev/null
mv ../../build/txt/43.txt ../../build/txt/043-oddish.txt 2>/dev/null
mv ../../build/html/44.html ../../build/html/044-gloom.html 2>/dev/null
mv ../../build/png/44.png ../../build/png/044-gloom.png 2>/dev/null
mv ../../build/txt/44.txt ../../build/txt/044-gloom.txt 2>/dev/null
mv ../../build/html/45.html ../../build/html/045-vileplume.html 2>/dev/null
mv ../../build/png/45.png ../../build/png/045-vileplume.png 2>/dev/null
mv ../../build/txt/45.txt ../../build/txt/045-vileplume.txt 2>/dev/null
mv ../../build/html/46.html ../../build/html/046-paras.html 2>/dev/null
mv ../../build/png/46.png ../../build/png/046-paras.png 2>/dev/null
mv ../../build/txt/46.txt ../../build/txt/046-paras.txt 2>/dev/null
mv ../../build/html/47.html ../../build/html/047-parasect.html 2>/dev/null
mv ../../build/png/47.png ../../build/png/047-parasect.png 2>/dev/null
mv ../../build/txt/47.txt ../../build/txt/047-parasect.txt 2>/dev/null
mv ../../build/html/48.html ../../build/html/048-venonat.html 2>/dev/null
mv ../../build/png/48.png ../../build/png/048-venonat.png 2>/dev/null
mv ../../build/txt/48.txt ../../build/txt/048-venonat.txt 2>/dev/null
mv ../../build/html/49.html ../../build/html/049-venomoth.html 2>/dev/null
mv ../../build/png/49.png ../../build/png/049-venomoth.png 2>/dev/null
mv ../../build/txt/49.txt ../../build/txt/049-venomoth.txt 2>/dev/null
mv ../../build/html/50.html ../../build/html/050-diglett.html 2>/dev/null
mv ../../build/png/50.png ../../build/png/050-diglett.png 2>/dev/null
mv ../../build/txt/50.txt ../../build/txt/050-diglett.txt 2>/dev/null
mv ../../build/html/51.html ../../build/html/051-dugtrio.html 2>/dev/null
mv ../../build/png/51.png ../../build/png/051-dugtrio.png 2>/dev/null
mv ../../build/txt/51.txt ../../build/txt/051-dugtrio.txt 2>/dev/null
mv ../../build/html/52.html ../../build/html/052-meowth.html 2>/dev/null
mv ../../build/png/52.png ../../build/png/052-meowth.png 2>/dev/null
mv ../../build/txt/52.txt ../../build/txt/052-meowth.txt 2>/dev/null
mv ../../build/html/53.html ../../build/html/053-persian.html 2>/dev/null
mv ../../build/png/53.png ../../build/png/053-persian.png 2>/dev/null
mv ../../build/txt/53.txt ../../build/txt/053-persian.txt 2>/dev/null
mv ../../build/html/54.html ../../build/html/054-psyduck.html 2>/dev/null
mv ../../build/png/54.png ../../build/png/054-psyduck.png 2>/dev/null
mv ../../build/txt/54.txt ../../build/txt/054-psyduck.txt 2>/dev/null
mv ../../build/html/55.html ../../build/html/055-golduck.html 2>/dev/null
mv ../../build/png/55.png ../../build/png/055-golduck.png 2>/dev/null
mv ../../build/txt/55.txt ../../build/txt/055-golduck.txt 2>/dev/null
mv ../../build/html/56.html ../../build/html/056-mankey.html 2>/dev/null
mv ../../build/png/56.png ../../build/png/056-mankey.png 2>/dev/null
mv ../../build/txt/56.txt ../../build/txt/056-mankey.txt 2>/dev/null
mv ../../build/html/57.html ../../build/html/057-primeape.html 2>/dev/null
mv ../../build/png/57.png ../../build/png/057-primeape.png 2>/dev/null
mv ../../build/txt/57.txt ../../build/txt/057-primeape.txt 2>/dev/null
mv ../../build/html/58.html ../../build/html/058-growlithe.html 2>/dev/null
mv ../../build/png/58.png ../../build/png/058-growlithe.png 2>/dev/null
mv ../../build/txt/58.txt ../../build/txt/058-growlithe.txt 2>/dev/null
mv ../../build/html/59.html ../../build/html/059-arcanine.html 2>/dev/null
mv ../../build/png/59.png ../../build/png/059-arcanine.png 2>/dev/null
mv ../../build/txt/59.txt ../../build/txt/059-arcanine.txt 2>/dev/null
mv ../../build/html/60.html ../../build/html/060-poliwag.html 2>/dev/null
mv ../../build/png/60.png ../../build/png/060-poliwag.png 2>/dev/null
mv ../../build/txt/60.txt ../../build/txt/060-poliwag.txt 2>/dev/null
mv ../../build/html/61.html ../../build/html/061-poliwhirl.html 2>/dev/null
mv ../../build/png/61.png ../../build/png/061-poliwhirl.png 2>/dev/null
mv ../../build/txt/61.txt ../../build/txt/061-poliwhirl.txt 2>/dev/null
mv ../../build/html/62.html ../../build/html/062-poliwrath.html 2>/dev/null
mv ../../build/png/62.png ../../build/png/062-poliwrath.png 2>/dev/null
mv ../../build/txt/62.txt ../../build/txt/062-poliwrath.txt 2>/dev/null
mv ../../build/html/63.html ../../build/html/063-abra.html 2>/dev/null
mv ../../build/png/63.png ../../build/png/063-abra.png 2>/dev/null
mv ../../build/txt/63.txt ../../build/txt/063-abra.txt 2>/dev/null
mv ../../build/html/64.html ../../build/html/064-kadabra.html 2>/dev/null
mv ../../build/png/64.png ../../build/png/064-kadabra.png 2>/dev/null
mv ../../build/txt/64.txt ../../build/txt/064-kadabra.txt 2>/dev/null
mv ../../build/html/65.html ../../build/html/065-alakazam.html 2>/dev/null
mv ../../build/png/65.png ../../build/png/065-alakazam.png 2>/dev/null
mv ../../build/txt/65.txt ../../build/txt/065-alakazam.txt 2>/dev/null
mv ../../build/html/66.html ../../build/html/066-machop.html 2>/dev/null
mv ../../build/png/66.png ../../build/png/066-machop.png 2>/dev/null
mv ../../build/txt/66.txt ../../build/txt/066-machop.txt 2>/dev/null
mv ../../build/html/67.html ../../build/html/067-machoke.html 2>/dev/null
mv ../../build/png/67.png ../../build/png/067-machoke.png 2>/dev/null
mv ../../build/txt/67.txt ../../build/txt/067-machoke.txt 2>/dev/null
mv ../../build/html/68.html ../../build/html/068-machamp.html 2>/dev/null
mv ../../build/png/68.png ../../build/png/068-machamp.png 2>/dev/null
mv ../../build/txt/68.txt ../../build/txt/068-machamp.txt 2>/dev/null
mv ../../build/html/69.html ../../build/html/069-bellsprout.html 2>/dev/null
mv ../../build/png/69.png ../../build/png/069-bellsprout.png 2>/dev/null
mv ../../build/txt/69.txt ../../build/txt/069-bellsprout.txt 2>/dev/null
mv ../../build/html/70.html ../../build/html/070-weepinbell.html 2>/dev/null
mv ../../build/png/70.png ../../build/png/070-weepinbell.png 2>/dev/null
mv ../../build/txt/70.txt ../../build/txt/070-weepinbell.txt 2>/dev/null
mv ../../build/html/71.html ../../build/html/071-victreebel.html 2>/dev/null
mv ../../build/png/71.png ../../build/png/071-victreebel.png 2>/dev/null
mv ../../build/txt/71.txt ../../build/txt/071-victreebel.txt 2>/dev/null
mv ../../build/html/72.html ../../build/html/072-tentacool.html 2>/dev/null
mv ../../build/png/72.png ../../build/png/072-tentacool.png 2>/dev/null
mv ../../build/txt/72.txt ../../build/txt/072-tentacool.txt 2>/dev/null
mv ../../build/html/73.html ../../build/html/073-tentacruel.html 2>/dev/null
mv ../../build/png/73.png ../../build/png/073-tentacruel.png 2>/dev/null
mv ../../build/txt/73.txt ../../build/txt/073-tentacruel.txt 2>/dev/null
mv ../../build/html/74.html ../../build/html/074-geodude.html 2>/dev/null
mv ../../build/png/74.png ../../build/png/074-geodude.png 2>/dev/null
mv ../../build/txt/74.txt ../../build/txt/074-geodude.txt 2>/dev/null
mv ../../build/html/75.html ../../build/html/075-graveler.html 2>/dev/null
mv ../../build/png/75.png ../../build/png/075-graveler.png 2>/dev/null
mv ../../build/txt/75.txt ../../build/txt/075-graveler.txt 2>/dev/null
mv ../../build/html/76.html ../../build/html/076-golem.html 2>/dev/null
mv ../../build/png/76.png ../../build/png/076-golem.png 2>/dev/null
mv ../../build/txt/76.txt ../../build/txt/076-golem.txt 2>/dev/null
mv ../../build/html/77.html ../../build/html/077-ponyta.html 2>/dev/null
mv ../../build/png/77.png ../../build/png/077-ponyta.png 2>/dev/null
mv ../../build/txt/77.txt ../../build/txt/077-ponyta.txt 2>/dev/null
mv ../../build/html/78.html ../../build/html/078-rapidash.html 2>/dev/null
mv ../../build/png/78.png ../../build/png/078-rapidash.png 2>/dev/null
mv ../../build/txt/78.txt ../../build/txt/078-rapidash.txt 2>/dev/null
mv ../../build/html/79.html ../../build/html/079-slowpoke.html 2>/dev/null
mv ../../build/png/79.png ../../build/png/079-slowpoke.png 2>/dev/null
mv ../../build/txt/79.txt ../../build/txt/079-slowpoke.txt 2>/dev/null
mv ../../build/html/80.html ../../build/html/080-slowbro.html 2>/dev/null
mv ../../build/png/80.png ../../build/png/080-slowbro.png 2>/dev/null
mv ../../build/txt/80.txt ../../build/txt/080-slowbro.txt 2>/dev/null
mv ../../build/html/81.html ../../build/html/081-magnemite.html 2>/dev/null
mv ../../build/png/81.png ../../build/png/081-magnemite.png 2>/dev/null
mv ../../build/txt/81.txt ../../build/txt/081-magnemite.txt 2>/dev/null
mv ../../build/html/82.html ../../build/html/082-magneton.html 2>/dev/null
mv ../../build/png/82.png ../../build/png/082-magneton.png 2>/dev/null
mv ../../build/txt/82.txt ../../build/txt/082-magneton.txt 2>/dev/null
mv ../../build/html/83.html ../../build/html/083-farfetchd.html 2>/dev/null
mv ../../build/png/83.png ../../build/png/083-farfetchd.png 2>/dev/null
mv ../../build/txt/83.txt ../../build/txt/083-farfetchd.txt 2>/dev/null
mv ../../build/html/84.html ../../build/html/084-doduo.html 2>/dev/null
mv ../../build/png/84.png ../../build/png/084-doduo.png 2>/dev/null
mv ../../build/txt/84.txt ../../build/txt/084-doduo.txt 2>/dev/null
mv ../../build/html/85.html ../../build/html/085-dodrio.html 2>/dev/null
mv ../../build/png/85.png ../../build/png/085-dodrio.png 2>/dev/null
mv ../../build/txt/85.txt ../../build/txt/085-dodrio.txt 2>/dev/null
mv ../../build/html/86.html ../../build/html/086-seel.html 2>/dev/null
mv ../../build/png/86.png ../../build/png/086-seel.png 2>/dev/null
mv ../../build/txt/86.txt ../../build/txt/086-seel.txt 2>/dev/null
mv ../../build/html/87.html ../../build/html/087-dewgong.html 2>/dev/null
mv ../../build/png/87.png ../../build/png/087-dewgong.png 2>/dev/null
mv ../../build/txt/87.txt ../../build/txt/087-dewgong.txt 2>/dev/null
mv ../../build/html/88.html ../../build/html/088-grimer.html 2>/dev/null
mv ../../build/png/88.png ../../build/png/088-grimer.png 2>/dev/null
mv ../../build/txt/88.txt ../../build/txt/088-grimer.txt 2>/dev/null
mv ../../build/html/89.html ../../build/html/089-muk.html 2>/dev/null
mv ../../build/png/89.png ../../build/png/089-muk.png 2>/dev/null
mv ../../build/txt/89.txt ../../build/txt/089-muk.txt 2>/dev/null
mv ../../build/html/90.html ../../build/html/090-shellder.html 2>/dev/null
mv ../../build/png/90.png ../../build/png/090-shellder.png 2>/dev/null
mv ../../build/txt/90.txt ../../build/txt/090-shellder.txt 2>/dev/null
mv ../../build/html/91.html ../../build/html/091-cloyster.html 2>/dev/null
mv ../../build/png/91.png ../../build/png/091-cloyster.png 2>/dev/null
mv ../../build/txt/91.txt ../../build/txt/091-cloyster.txt 2>/dev/null
mv ../../build/html/92.html ../../build/html/092-gastly.html 2>/dev/null
mv ../../build/png/92.png ../../build/png/092-gastly.png 2>/dev/null
mv ../../build/txt/92.txt ../../build/txt/092-gastly.txt 2>/dev/null
mv ../../build/html/93.html ../../build/html/093-haunter.html 2>/dev/null
mv ../../build/png/93.png ../../build/png/093-haunter.png 2>/dev/null
mv ../../build/txt/93.txt ../../build/txt/093-haunter.txt 2>/dev/null
mv ../../build/html/94.html ../../build/html/094-gengar.html 2>/dev/null
mv ../../build/png/94.png ../../build/png/094-gengar.png 2>/dev/null
mv ../../build/txt/94.txt ../../build/txt/094-gengar.txt 2>/dev/null
mv ../../build/html/95.html ../../build/html/095-onix.html 2>/dev/null
mv ../../build/png/95.png ../../build/png/095-onix.png 2>/dev/null
mv ../../build/txt/95.txt ../../build/txt/095-onix.txt 2>/dev/null
mv ../../build/html/96.html ../../build/html/096-drowzee.html 2>/dev/null
mv ../../build/png/96.png ../../build/png/096-drowzee.png 2>/dev/null
mv ../../build/txt/96.txt ../../build/txt/096-drowzee.txt 2>/dev/null
mv ../../build/html/97.html ../../build/html/097-hypno.html 2>/dev/null
mv ../../build/png/97.png ../../build/png/097-hypno.png 2>/dev/null
mv ../../build/txt/97.txt ../../build/txt/097-hypno.txt 2>/dev/null
mv ../../build/html/98.html ../../build/html/098-krabby.html 2>/dev/null
mv ../../build/png/98.png ../../build/png/098-krabby.png 2>/dev/null
mv ../../build/txt/98.txt ../../build/txt/098-krabby.txt 2>/dev/null
mv ../../build/html/99.html ../../build/html/099-kingler.html 2>/dev/null
mv ../../build/png/99.png ../../build/png/099-kingler.png 2>/dev/null
mv ../../build/txt/99.txt ../../build/txt/099-kingler.txt 2>/dev/null
mv ../../build/html/100.html ../../build/html/100-voltorb.html 2>/dev/null
mv ../../build/png/100.png ../../build/png/100-voltorb.png 2>/dev/null
mv ../../build/txt/100.txt ../../build/txt/100-voltorb.txt 2>/dev/null
mv ../../build/html/101.html ../../build/html/101-electrode.html 2>/dev/null
mv ../../build/png/101.png ../../build/png/101-electrode.png 2>/dev/null
mv ../../build/txt/101.txt ../../build/txt/101-electrode.txt 2>/dev/null
mv ../../build/html/102.html ../../build/html/102-exeggcute.html 2>/dev/null
mv ../../build/png/102.png ../../build/png/102-exeggcute.png 2>/dev/null
mv ../../build/txt/102.txt ../../build/txt/102-exeggcute.txt 2>/dev/null
mv ../../build/html/103.html ../../build/html/103-exeggutor.html 2>/dev/null
mv ../../build/png/103.png ../../build/png/103-exeggutor.png 2>/dev/null
mv ../../build/txt/103.txt ../../build/txt/103-exeggutor.txt 2>/dev/null
mv ../../build/html/104.html ../../build/html/104-cubone.html 2>/dev/null
mv ../../build/png/104.png ../../build/png/104-cubone.png 2>/dev/null
mv ../../build/txt/104.txt ../../build/txt/104-cubone.txt 2>/dev/null
mv ../../build/html/105.html ../../build/html/105-marowak.html 2>/dev/null
mv ../../build/png/105.png ../../build/png/105-marowak.png 2>/dev/null
mv ../../build/txt/105.txt ../../build/txt/105-marowak.txt 2>/dev/null
mv ../../build/html/106.html ../../build/html/106-hitmonlee.html 2>/dev/null
mv ../../build/png/106.png ../../build/png/106-hitmonlee.png 2>/dev/null
mv ../../build/txt/106.txt ../../build/txt/106-hitmonlee.txt 2>/dev/null
mv ../../build/html/107.html ../../build/html/107-hitmonchan.html 2>/dev/null
mv ../../build/png/107.png ../../build/png/107-hitmonchan.png 2>/dev/null
mv ../../build/txt/107.txt ../../build/txt/107-hitmonchan.txt 2>/dev/null
mv ../../build/html/108.html ../../build/html/108-lickitung.html 2>/dev/null
mv ../../build/png/108.png ../../build/png/108-lickitung.png 2>/dev/null
mv ../../build/txt/108.txt ../../build/txt/108-lickitung.txt 2>/dev/null
mv ../../build/html/109.html ../../build/html/109-koffing.html 2>/dev/null
mv ../../build/png/109.png ../../build/png/109-koffing.png 2>/dev/null
mv ../../build/txt/109.txt ../../build/txt/109-koffing.txt 2>/dev/null
mv ../../build/html/110.html ../../build/html/110-weezing.html 2>/dev/null
mv ../../build/png/110.png ../../build/png/110-weezing.png 2>/dev/null
mv ../../build/txt/110.txt ../../build/txt/110-weezing.txt 2>/dev/null
mv ../../build/html/111.html ../../build/html/111-rhyhorn.html 2>/dev/null
mv ../../build/png/111.png ../../build/png/111-rhyhorn.png 2>/dev/null
mv ../../build/txt/111.txt ../../build/txt/111-rhyhorn.txt 2>/dev/null
mv ../../build/html/112.html ../../build/html/112-rhydon.html 2>/dev/null
mv ../../build/png/112.png ../../build/png/112-rhydon.png 2>/dev/null
mv ../../build/txt/112.txt ../../build/txt/112-rhydon.txt 2>/dev/null
mv ../../build/html/113.html ../../build/html/113-chansey.html 2>/dev/null
mv ../../build/png/113.png ../../build/png/113-chansey.png 2>/dev/null
mv ../../build/txt/113.txt ../../build/txt/113-chansey.txt 2>/dev/null
mv ../../build/html/114.html ../../build/html/114-tangela.html 2>/dev/null
mv ../../build/png/114.png ../../build/png/114-tangela.png 2>/dev/null
mv ../../build/txt/114.txt ../../build/txt/114-tangela.txt 2>/dev/null
mv ../../build/html/115.html ../../build/html/115-kangaskhan.html 2>/dev/null
mv ../../build/png/115.png ../../build/png/115-kangaskhan.png 2>/dev/null
mv ../../build/txt/115.txt ../../build/txt/115-kangaskhan.txt 2>/dev/null
mv ../../build/html/116.html ../../build/html/116-horsea.html 2>/dev/null
mv ../../build/png/116.png ../../build/png/116-horsea.png 2>/dev/null
mv ../../build/txt/116.txt ../../build/txt/116-horsea.txt 2>/dev/null
mv ../../build/html/117.html ../../build/html/117-seadra.html 2>/dev/null
mv ../../build/png/117.png ../../build/png/117-seadra.png 2>/dev/null
mv ../../build/txt/117.txt ../../build/txt/117-seadra.txt 2>/dev/null
mv ../../build/html/118.html ../../build/html/118-goldeen.html 2>/dev/null
mv ../../build/png/118.png ../../build/png/118-goldeen.png 2>/dev/null
mv ../../build/txt/118.txt ../../build/txt/118-goldeen.txt 2>/dev/null
mv ../../build/html/119.html ../../build/html/119-seaking.html 2>/dev/null
mv ../../build/png/119.png ../../build/png/119-seaking.png 2>/dev/null
mv ../../build/txt/119.txt ../../build/txt/119-seaking.txt 2>/dev/null
mv ../../build/html/120.html ../../build/html/120-staryu.html 2>/dev/null
mv ../../build/png/120.png ../../build/png/120-staryu.png 2>/dev/null
mv ../../build/txt/120.txt ../../build/txt/120-staryu.txt 2>/dev/null
mv ../../build/html/121.html ../../build/html/121-starmie.html 2>/dev/null
mv ../../build/png/121.png ../../build/png/121-starmie.png 2>/dev/null
mv ../../build/txt/121.txt ../../build/txt/121-starmie.txt 2>/dev/null
mv ../../build/html/122.html ../../build/html/122-mr-mime.html 2>/dev/null
mv ../../build/png/122.png ../../build/png/122-mr-mime.png 2>/dev/null
mv ../../build/txt/122.txt ../../build/png/122-mr-mime.txt 2>/dev/null
mv ../../build/html/123.html ../../build/html/123-scyther.html 2>/dev/null
mv ../../build/png/123.png ../../build/png/123-scyther.png 2>/dev/null
mv ../../build/txt/123.txt ../../build/txt/123-scyther.txt 2>/dev/null
mv ../../build/html/124.html ../../build/html/124-jynx.html 2>/dev/null
mv ../../build/png/124.png ../../build/png/124-jynx.png 2>/dev/null
mv ../../build/txt/124.txt ../../build/txt/124-jynx.txt 2>/dev/null
mv ../../build/html/125.html ../../build/html/125-electabuzz.html 2>/dev/null
mv ../../build/png/125.png ../../build/png/125-electabuzz.png 2>/dev/null
mv ../../build/txt/125.txt ../../build/txt/125-electabuzz.txt 2>/dev/null
mv ../../build/html/126.html ../../build/html/126-magmar.html 2>/dev/null
mv ../../build/png/126.png ../../build/png/126-magmar.png 2>/dev/null
mv ../../build/txt/126.txt ../../build/txt/126-magmar.txt 2>/dev/null
mv ../../build/html/127.html ../../build/html/127-pinsir.html 2>/dev/null
mv ../../build/png/127.png ../../build/png/127-pinsir.png 2>/dev/null
mv ../../build/txt/127.txt ../../build/txt/127-pinsir.txt 2>/dev/null
mv ../../build/html/128.html ../../build/html/128-tauros.html 2>/dev/null
mv ../../build/png/128.png ../../build/png/128-tauros.png 2>/dev/null
mv ../../build/txt/128.txt ../../build/txt/128-tauros.txt 2>/dev/null
mv ../../build/html/129.html ../../build/html/129-magikarp.html 2>/dev/null
mv ../../build/png/129.png ../../build/png/129-magikarp.png 2>/dev/null
mv ../../build/txt/129.txt ../../build/txt/129-magikarp.txt 2>/dev/null
mv ../../build/html/130.html ../../build/html/130-gyarados.html 2>/dev/null
mv ../../build/png/130.png ../../build/png/130-gyarados.png 2>/dev/null
mv ../../build/txt/130.txt ../../build/txt/130-gyarados.txt 2>/dev/null
mv ../../build/html/131.html ../../build/html/131-lapras.html 2>/dev/null
mv ../../build/png/131.png ../../build/png/131-lapras.png 2>/dev/null
mv ../../build/txt/131.txt ../../build/txt/131-lapras.txt 2>/dev/null
mv ../../build/html/132.html ../../build/html/132-ditto.html 2>/dev/null
mv ../../build/png/132.png ../../build/png/132-ditto.png 2>/dev/null
mv ../../build/txt/132.txt ../../build/txt/132-ditto.txt 2>/dev/null
mv ../../build/html/133.html ../../build/html/133-eevee.html 2>/dev/null
mv ../../build/png/133.png ../../build/png/133-eevee.png 2>/dev/null
mv ../../build/txt/133.txt ../../build/txt/133-eevee.txt 2>/dev/null
mv ../../build/html/134.html ../../build/html/134-vaporeon.html 2>/dev/null
mv ../../build/png/134.png ../../build/png/134-vaporeon.png 2>/dev/null
mv ../../build/txt/134.txt ../../build/txt/134-vaporeon.txt 2>/dev/null
mv ../../build/html/135.html ../../build/html/135-jolteon.html 2>/dev/null
mv ../../build/png/135.png ../../build/png/135-jolteon.png 2>/dev/null
mv ../../build/txt/135.txt ../../build/txt/135-jolteon.txt 2>/dev/null
mv ../../build/html/136.html ../../build/html/136-flareon.html 2>/dev/null
mv ../../build/png/136.png ../../build/png/136-flareon.png 2>/dev/null
mv ../../build/txt/136.txt ../../build/txt/136-flareon.txt 2>/dev/null
mv ../../build/html/137.html ../../build/html/137-porygon.html 2>/dev/null
mv ../../build/png/137.png ../../build/png/137-porygon.png 2>/dev/null
mv ../../build/txt/137.txt ../../build/txt/137-porygon.txt 2>/dev/null
mv ../../build/html/138.html ../../build/html/138-omanyte.html 2>/dev/null
mv ../../build/png/138.png ../../build/png/138-omanyte.png 2>/dev/null
mv ../../build/txt/138.txt ../../build/txt/138-omanyte.txt 2>/dev/null
mv ../../build/html/139.html ../../build/html/139-omastar.html 2>/dev/null
mv ../../build/png/139.png ../../build/png/139-omastar.png 2>/dev/null
mv ../../build/txt/139.txt ../../build/txt/139-omastar.txt 2>/dev/null
mv ../../build/html/140.html ../../build/html/140-kabuto.html 2>/dev/null
mv ../../build/png/140.png ../../build/png/140-kabuto.png 2>/dev/null
mv ../../build/txt/140.txt ../../build/txt/140-kabuto.txt 2>/dev/null
mv ../../build/html/141.html ../../build/html/141-kabutops.html 2>/dev/null
mv ../../build/png/141.png ../../build/png/141-kabutops.png 2>/dev/null
mv ../../build/txt/141.txt ../../build/txt/141-kabutops.txt 2>/dev/null
mv ../../build/html/142.html ../../build/html/142-aerodactyl.html 2>/dev/null
mv ../../build/png/142.png ../../build/png/142-aerodactyl.png 2>/dev/null
mv ../../build/txt/142.txt ../../build/txt/142-aerodactyl.txt 2>/dev/null
mv ../../build/html/143.html ../../build/html/143-snorlax.html 2>/dev/null
mv ../../build/png/143.png ../../build/png/143-snorlax.png 2>/dev/null
mv ../../build/txt/143.txt ../../build/txt/143-snorlax.txt 2>/dev/null
mv ../../build/html/144.html ../../build/html/144-articuno.html 2>/dev/null
mv ../../build/png/144.png ../../build/png/144-articuno.png 2>/dev/null
mv ../../build/txt/144.txt ../../build/txt/144-articuno.txt 2>/dev/null
mv ../../build/html/145.html ../../build/html/145-zapdos.html 2>/dev/null
mv ../../build/png/145.png ../../build/png/145-zapdos.png 2>/dev/null
mv ../../build/txt/145.txt ../../build/txt/145-zapdos.txt 2>/dev/null
mv ../../build/html/146.html ../../build/html/146-moltres.html 2>/dev/null
mv ../../build/png/146.png ../../build/png/146-moltres.png 2>/dev/null
mv ../../build/txt/146.txt ../../build/txt/146-moltres.txt 2>/dev/null
mv ../../build/html/147.html ../../build/html/147-dratini.html 2>/dev/null
mv ../../build/png/147.png ../../build/png/147-dratini.png 2>/dev/null
mv ../../build/txt/147.txt ../../build/txt/147-dratini.txt 2>/dev/null
mv ../../build/html/148.html ../../build/html/148-dragonair.html 2>/dev/null
mv ../../build/png/148.png ../../build/png/148-dragonair.png 2>/dev/null
mv ../../build/txt/148.txt ../../build/txt/148-dragonair.txt 2>/dev/null
mv ../../build/html/149.html ../../build/html/149-dragonite.html 2>/dev/null
mv ../../build/png/149.png ../../build/png/149-dragonite.png 2>/dev/null
mv ../../build/txt/149.txt ../../build/txt/149-dragonite.txt 2>/dev/null
mv ../../build/html/150.html ../../build/html/150-mewtwo.html 2>/dev/null
mv ../../build/png/150.png ../../build/png/150-mewtwo.png 2>/dev/null
mv ../../build/txt/150.txt ../../build/txt/150-mewtwo.txt 2>/dev/null
mv ../../build/html/151.html ../../build/html/151-mew.html 2>/dev/null
mv ../../build/png/151.png ../../build/png/151-mew.png 2>/dev/null
mv ../../build/txt/151.txt ../../build/txt/151-mew.txt 2>/dev/null
mv ../../build/html/152.html ../../build/html/152-chikorita.html 2>/dev/null
mv ../../build/png/152.png ../../build/png/152-chikorita.png 2>/dev/null
mv ../../build/txt/152.txt ../../build/txt/152-chikorita.txt 2>/dev/null
mv ../../build/html/153.html ../../build/html/153-bayleef.html 2>/dev/null
mv ../../build/png/153.png ../../build/png/153-bayleef.png 2>/dev/null
mv ../../build/txt/153.txt ../../build/txt/153-bayleef.txt 2>/dev/null
mv ../../build/html/154.html ../../build/html/154-meganium.html 2>/dev/null
mv ../../build/png/154.png ../../build/png/154-meganium.png 2>/dev/null
mv ../../build/txt/154.txt ../../build/txt/154-meganium.txt 2>/dev/null
mv ../../build/html/155.html ../../build/html/155-cyndaquil.html 2>/dev/null
mv ../../build/png/155.png ../../build/png/155-cyndaquil.png 2>/dev/null
mv ../../build/txt/155.txt ../../build/txt/155-cyndaquil.txt 2>/dev/null
mv ../../build/html/156.html ../../build/html/156-quilava.html 2>/dev/null
mv ../../build/png/156.png ../../build/png/156-quilava.png 2>/dev/null
mv ../../build/txt/156.txt ../../build/txt/156-quilava.txt 2>/dev/null
mv ../../build/html/157.html ../../build/html/157-typhlosion.html 2>/dev/null
mv ../../build/png/157.png ../../build/png/157-typhlosion.png 2>/dev/null
mv ../../build/txt/157.txt ../../build/txt/157-typhlosion.txt 2>/dev/null
mv ../../build/html/158.html ../../build/html/158-totodile.html 2>/dev/null
mv ../../build/png/158.png ../../build/png/158-totodile.png 2>/dev/null
mv ../../build/txt/158.txt ../../build/txt/158-totodile.txt 2>/dev/null
mv ../../build/html/159.html ../../build/html/159-croconaw.html 2>/dev/null
mv ../../build/png/159.png ../../build/png/159-croconaw.png 2>/dev/null
mv ../../build/txt/159.txt ../../build/txt/159-croconaw.txt 2>/dev/null
mv ../../build/html/160.html ../../build/html/160-feraligatr.html 2>/dev/null
mv ../../build/png/160.png ../../build/png/160-feraligatr.png 2>/dev/null
mv ../../build/txt/160.txt ../../build/txt/160-feraligatr.txt 2>/dev/null
mv ../../build/html/161.html ../../build/html/161-sentret.html 2>/dev/null
mv ../../build/png/161.png ../../build/png/161-sentret.png 2>/dev/null
mv ../../build/txt/161.txt ../../build/txt/161-sentret.txt 2>/dev/null
mv ../../build/html/162.html ../../build/html/162-furret.html 2>/dev/null
mv ../../build/png/162.png ../../build/png/162-furret.png 2>/dev/null
mv ../../build/txt/162.txt ../../build/txt/162-furret.txt 2>/dev/null
mv ../../build/html/163.html ../../build/html/163-hoothoot.html 2>/dev/null
mv ../../build/png/163.png ../../build/png/163-hoothoot.png 2>/dev/null
mv ../../build/txt/163.txt ../../build/txt/163-hoothoot.txt 2>/dev/null
mv ../../build/html/164.html ../../build/html/164-noctowl.html 2>/dev/null
mv ../../build/png/164.png ../../build/png/164-noctowl.png 2>/dev/null
mv ../../build/txt/164.txt ../../build/txt/164-noctowl.txt 2>/dev/null
mv ../../build/html/165.html ../../build/html/165-ledyba.html 2>/dev/null
mv ../../build/png/165.png ../../build/png/165-ledyba.png 2>/dev/null
mv ../../build/txt/165.txt ../../build/txt/165-ledyba.txt 2>/dev/null
mv ../../build/html/166.html ../../build/html/166-ledian.html 2>/dev/null
mv ../../build/png/166.png ../../build/png/166-ledian.png 2>/dev/null
mv ../../build/txt/166.txt ../../build/txt/166-ledian.txt 2>/dev/null
mv ../../build/html/167.html ../../build/html/167-spinarak.html 2>/dev/null
mv ../../build/png/167.png ../../build/png/167-spinarak.png 2>/dev/null
mv ../../build/txt/167.txt ../../build/txt/167-spinarak.txt 2>/dev/null
mv ../../build/html/168.html ../../build/html/168-ariados.html 2>/dev/null
mv ../../build/png/168.png ../../build/png/168-ariados.png 2>/dev/null
mv ../../build/txt/168.txt ../../build/txt/168-ariados.txt 2>/dev/null
mv ../../build/html/169.html ../../build/html/169-crobat.html 2>/dev/null
mv ../../build/png/169.png ../../build/png/169-crobat.png 2>/dev/null
mv ../../build/txt/169.txt ../../build/txt/169-crobat.txt 2>/dev/null
mv ../../build/html/170.html ../../build/html/170-chinchou.html 2>/dev/null
mv ../../build/png/170.png ../../build/png/170-chinchou.png 2>/dev/null
mv ../../build/txt/170.txt ../../build/txt/170-chinchou.txt 2>/dev/null
mv ../../build/html/171.html ../../build/html/171-lanturn.html 2>/dev/null
mv ../../build/png/171.png ../../build/png/171-lanturn.png 2>/dev/null
mv ../../build/txt/171.txt ../../build/txt/171-lanturn.txt 2>/dev/null
mv ../../build/html/172.html ../../build/html/172-pichu.html 2>/dev/null
mv ../../build/png/172.png ../../build/png/172-pichu.png 2>/dev/null
mv ../../build/txt/172.txt ../../build/txt/172-pichu.txt 2>/dev/null
mv ../../build/html/173.html ../../build/html/173-cleffa.html 2>/dev/null
mv ../../build/png/173.png ../../build/png/173-cleffa.png 2>/dev/null
mv ../../build/txt/173.txt ../../build/txt/173-cleffa.txt 2>/dev/null
mv ../../build/html/174.html ../../build/html/174-igglybuff.html 2>/dev/null
mv ../../build/png/174.png ../../build/png/174-igglybuff.png 2>/dev/null
mv ../../build/txt/174.txt ../../build/txt/174-igglybuff.txt 2>/dev/null
mv ../../build/html/175.html ../../build/html/175-togepi.html 2>/dev/null
mv ../../build/png/175.png ../../build/png/175-togepi.png 2>/dev/null
mv ../../build/txt/175.txt ../../build/txt/175-togepi.txt 2>/dev/null
mv ../../build/html/176.html ../../build/html/176-togetic.html 2>/dev/null
mv ../../build/png/176.png ../../build/png/176-togetic.png 2>/dev/null
mv ../../build/txt/176.txt ../../build/txt/176-togetic.txt 2>/dev/null
mv ../../build/html/177.html ../../build/html/177-natu.html 2>/dev/null
mv ../../build/png/177.png ../../build/png/177-natu.png 2>/dev/null
mv ../../build/txt/177.txt ../../build/txt/177-natu.txt 2>/dev/null
mv ../../build/html/178.html ../../build/html/178-xatu.html 2>/dev/null
mv ../../build/png/178.png ../../build/png/178-xatu.png 2>/dev/null
mv ../../build/txt/178.txt ../../build/txt/178-xatu.txt 2>/dev/null
mv ../../build/html/179.html ../../build/html/179-mareep.html 2>/dev/null
mv ../../build/png/179.png ../../build/png/179-mareep.png 2>/dev/null
mv ../../build/txt/179.txt ../../build/txt/179-mareep.txt 2>/dev/null
mv ../../build/html/180.html ../../build/html/180-flaaffy.html 2>/dev/null
mv ../../build/png/180.png ../../build/png/180-flaaffy.png 2>/dev/null
mv ../../build/txt/180.txt ../../build/txt/180-flaaffy.txt 2>/dev/null
mv ../../build/html/181.html ../../build/html/181-ampharos.html 2>/dev/null
mv ../../build/png/181.png ../../build/png/181-ampharos.png 2>/dev/null
mv ../../build/txt/181.txt ../../build/txt/181-ampharos.txt 2>/dev/null
mv ../../build/html/182.html ../../build/html/182-bellossom.html 2>/dev/null
mv ../../build/png/182.png ../../build/png/182-bellossom.png 2>/dev/null
mv ../../build/txt/182.txt ../../build/txt/182-bellossom.txt 2>/dev/null
mv ../../build/html/183.html ../../build/html/183-marill.html 2>/dev/null
mv ../../build/png/183.png ../../build/png/183-marill.png 2>/dev/null
mv ../../build/txt/183.txt ../../build/txt/183-marill.txt 2>/dev/null
mv ../../build/html/184.html ../../build/html/184-azumarill.html 2>/dev/null
mv ../../build/png/184.png ../../build/png/184-azumarill.png 2>/dev/null
mv ../../build/txt/184.txt ../../build/txt/184-azumarill.txt 2>/dev/null
mv ../../build/html/185.html ../../build/html/185-sudowoodo.html 2>/dev/null
mv ../../build/png/185.png ../../build/png/185-sudowoodo.png 2>/dev/null
mv ../../build/txt/185.txt ../../build/txt/185-sudowoodo.txt 2>/dev/null
mv ../../build/html/186.html ../../build/html/186-politoed.html 2>/dev/null
mv ../../build/png/186.png ../../build/png/186-politoed.png 2>/dev/null
mv ../../build/txt/186.txt ../../build/txt/186-politoed.txt 2>/dev/null
mv ../../build/html/187.html ../../build/html/187-hoppip.html 2>/dev/null
mv ../../build/png/187.png ../../build/png/187-hoppip.png 2>/dev/null
mv ../../build/txt/187.txt ../../build/txt/187-hoppip.txt 2>/dev/null
mv ../../build/html/188.html ../../build/html/188-skiploom.html 2>/dev/null
mv ../../build/png/188.png ../../build/png/188-skiploom.png 2>/dev/null
mv ../../build/txt/188.txt ../../build/txt/188-skiploom.txt 2>/dev/null
mv ../../build/html/189.html ../../build/html/189-jumpluff.html 2>/dev/null
mv ../../build/png/189.png ../../build/png/189-jumpluff.png 2>/dev/null
mv ../../build/txt/189.txt ../../build/txt/189-jumpluff.txt 2>/dev/null
mv ../../build/html/190.html ../../build/html/190-aipom.html 2>/dev/null
mv ../../build/png/190.png ../../build/png/190-aipom.png 2>/dev/null
mv ../../build/txt/190.txt ../../build/txt/190-aipom.txt 2>/dev/null
mv ../../build/html/191.html ../../build/html/191-sunkern.html 2>/dev/null
mv ../../build/png/191.png ../../build/png/191-sunkern.png 2>/dev/null
mv ../../build/txt/191.txt ../../build/txt/191-sunkern.txt 2>/dev/null
mv ../../build/html/192.html ../../build/html/192-sunflora.html 2>/dev/null
mv ../../build/png/192.png ../../build/png/192-sunflora.png 2>/dev/null
mv ../../build/txt/192.txt ../../build/txt/192-sunflora.txt 2>/dev/null
mv ../../build/html/193.html ../../build/html/193-yanma.html 2>/dev/null
mv ../../build/png/193.png ../../build/png/193-yanma.png 2>/dev/null
mv ../../build/txt/193.txt ../../build/txt/193-yanma.txt 2>/dev/null
mv ../../build/html/194.html ../../build/html/194-wooper.html 2>/dev/null
mv ../../build/png/194.png ../../build/png/194-wooper.png 2>/dev/null
mv ../../build/txt/194.txt ../../build/txt/194-wooper.txt 2>/dev/null
mv ../../build/html/195.html ../../build/html/195-quagsire.html 2>/dev/null
mv ../../build/png/195.png ../../build/png/195-quagsire.png 2>/dev/null
mv ../../build/txt/195.txt ../../build/txt/195-quagsire.txt 2>/dev/null
mv ../../build/html/196.html ../../build/html/196-espeon.html 2>/dev/null
mv ../../build/png/196.png ../../build/png/196-espeon.png 2>/dev/null
mv ../../build/txt/196.txt ../../build/txt/196-espeon.txt 2>/dev/null
mv ../../build/html/197.html ../../build/html/197-umbreon.html 2>/dev/null
mv ../../build/png/197.png ../../build/png/197-umbreon.png 2>/dev/null
mv ../../build/txt/197.txt ../../build/txt/197-umbreon.txt 2>/dev/null
mv ../../build/html/198.html ../../build/html/198-murkrow.html 2>/dev/null
mv ../../build/png/198.png ../../build/png/198-murkrow.png 2>/dev/null
mv ../../build/txt/198.txt ../../build/txt/198-murkrow.txt 2>/dev/null
mv ../../build/html/199.html ../../build/html/199-slowking.html 2>/dev/null
mv ../../build/png/199.png ../../build/png/199-slowking.png 2>/dev/null
mv ../../build/txt/199.txt ../../build/txt/199-slowking.txt 2>/dev/null
mv ../../build/html/200.html ../../build/html/200-misdreavus.html 2>/dev/null
mv ../../build/png/200.png ../../build/png/200-misdreavus.png 2>/dev/null
mv ../../build/txt/200.txt ../../build/txt/200-misdreavus.txt 2>/dev/null
mv ../../build/html/201.html ../../build/html/201-unown.html 2>/dev/null
mv ../../build/png/201.png ../../build/png/201-unown.png 2>/dev/null
mv ../../build/txt/201.txt ../../build/txt/201-unown.txt 2>/dev/null
mv ../../build/html/202.html ../../build/html/202-wobbuffet.html 2>/dev/null
mv ../../build/png/202.png ../../build/png/202-wobbuffet.png 2>/dev/null
mv ../../build/txt/202.txt ../../build/txt/202-wobbuffet.txt 2>/dev/null
mv ../../build/html/203.html ../../build/html/203-girafarig.html 2>/dev/null
mv ../../build/png/203.png ../../build/png/203-girafarig.png 2>/dev/null
mv ../../build/txt/203.txt ../../build/txt/203-girafarig.txt 2>/dev/null
mv ../../build/html/204.html ../../build/html/204-pineco.html 2>/dev/null
mv ../../build/png/204.png ../../build/png/204-pineco.png 2>/dev/null
mv ../../build/txt/204.txt ../../build/txt/204-pineco.txt 2>/dev/null
mv ../../build/html/205.html ../../build/html/205-forretress.html 2>/dev/null
mv ../../build/png/205.png ../../build/png/205-forretress.png 2>/dev/null
mv ../../build/txt/205.txt ../../build/txt/205-forretress.txt 2>/dev/null
mv ../../build/html/206.html ../../build/html/206-dunsparce.html 2>/dev/null
mv ../../build/png/206.png ../../build/png/206-dunsparce.png 2>/dev/null
mv ../../build/txt/206.txt ../../build/txt/206-dunsparce.txt 2>/dev/null
mv ../../build/html/207.html ../../build/html/207-gligar.html 2>/dev/null
mv ../../build/png/207.png ../../build/png/207-gligar.png 2>/dev/null
mv ../../build/txt/207.txt ../../build/txt/207-gligar.txt 2>/dev/null
mv ../../build/html/208.html ../../build/html/208-steelix.html 2>/dev/null
mv ../../build/png/208.png ../../build/png/208-steelix.png 2>/dev/null
mv ../../build/txt/208.txt ../../build/txt/208-steelix.txt 2>/dev/null
mv ../../build/html/209.html ../../build/html/209-snubbull.html 2>/dev/null
mv ../../build/png/209.png ../../build/png/209-snubbull.png 2>/dev/null
mv ../../build/txt/209.txt ../../build/txt/209-snubbull.txt 2>/dev/null
mv ../../build/html/210.html ../../build/html/210-granbull.html 2>/dev/null
mv ../../build/png/210.png ../../build/png/210-granbull.png 2>/dev/null
mv ../../build/txt/210.txt ../../build/txt/210-granbull.txt 2>/dev/null
mv ../../build/html/211.html ../../build/html/211-qwilfish.html 2>/dev/null
mv ../../build/png/211.png ../../build/png/211-qwilfish.png 2>/dev/null
mv ../../build/txt/211.txt ../../build/txt/211-qwilfish.txt 2>/dev/null
mv ../../build/html/212.html ../../build/html/212-scizor.html 2>/dev/null
mv ../../build/png/212.png ../../build/png/212-scizor.png 2>/dev/null
mv ../../build/txt/212.txt ../../build/txt/212-scizor.txt 2>/dev/null
mv ../../build/html/213.html ../../build/html/213-shuckle.html 2>/dev/null
mv ../../build/png/213.png ../../build/png/213-shuckle.png 2>/dev/null
mv ../../build/txt/213.txt ../../build/txt/213-shuckle.txt 2>/dev/null
mv ../../build/html/214.html ../../build/html/214-heracross.html 2>/dev/null
mv ../../build/png/214.png ../../build/png/214-heracross.png 2>/dev/null
mv ../../build/txt/214.txt ../../build/txt/214-heracross.txt 2>/dev/null
mv ../../build/html/215.html ../../build/html/215-sneasel.html 2>/dev/null
mv ../../build/png/215.png ../../build/png/215-sneasel.png 2>/dev/null
mv ../../build/txt/215.txt ../../build/txt/215-sneasel.txt 2>/dev/null
mv ../../build/html/216.html ../../build/html/216-teddiursa.html 2>/dev/null
mv ../../build/png/216.png ../../build/png/216-teddiursa.png 2>/dev/null
mv ../../build/txt/216.txt ../../build/txt/216-teddiursa.txt 2>/dev/null
mv ../../build/html/217.html ../../build/html/217-ursaring.html 2>/dev/null
mv ../../build/png/217.png ../../build/png/217-ursaring.png 2>/dev/null
mv ../../build/txt/217.txt ../../build/txt/217-ursaring.txt 2>/dev/null
mv ../../build/html/218.html ../../build/html/218-slugma.html 2>/dev/null
mv ../../build/png/218.png ../../build/png/218-slugma.png 2>/dev/null
mv ../../build/txt/218.txt ../../build/txt/218-slugma.txt 2>/dev/null
mv ../../build/html/219.html ../../build/html/219-magcargo.html 2>/dev/null
mv ../../build/png/219.png ../../build/png/219-magcargo.png 2>/dev/null
mv ../../build/txt/219.txt ../../build/txt/219-magcargo.txt 2>/dev/null
mv ../../build/html/220.html ../../build/html/220-swinub.html 2>/dev/null
mv ../../build/png/220.png ../../build/png/220-swinub.png 2>/dev/null
mv ../../build/txt/220.txt ../../build/txt/220-swinub.txt 2>/dev/null
mv ../../build/html/221.html ../../build/html/221-piloswine.html 2>/dev/null
mv ../../build/png/221.png ../../build/png/221-piloswine.png 2>/dev/null
mv ../../build/txt/221.txt ../../build/txt/221-piloswine.txt 2>/dev/null
mv ../../build/html/222.html ../../build/html/222-corsola.html 2>/dev/null
mv ../../build/png/222.png ../../build/png/222-corsola.png 2>/dev/null
mv ../../build/txt/222.txt ../../build/txt/222-corsola.txt 2>/dev/null
mv ../../build/html/223.html ../../build/html/223-remoraid.html 2>/dev/null
mv ../../build/png/223.png ../../build/png/223-remoraid.png 2>/dev/null
mv ../../build/txt/223.txt ../../build/txt/223-remoraid.txt 2>/dev/null
mv ../../build/html/224.html ../../build/html/224-octillery.html 2>/dev/null
mv ../../build/png/224.png ../../build/png/224-octillery.png 2>/dev/null
mv ../../build/txt/224.txt ../../build/txt/224-octillery.txt 2>/dev/null
mv ../../build/html/225.html ../../build/html/225-delibird.html 2>/dev/null
mv ../../build/png/225.png ../../build/png/225-delibird.png 2>/dev/null
mv ../../build/txt/225.txt ../../build/txt/225-delibird.txt 2>/dev/null
mv ../../build/html/226.html ../../build/html/226-mantine.html 2>/dev/null
mv ../../build/png/226.png ../../build/png/226-mantine.png 2>/dev/null
mv ../../build/txt/226.txt ../../build/txt/226-mantine.txt 2>/dev/null
mv ../../build/html/227.html ../../build/html/227-skarmory.html 2>/dev/null
mv ../../build/png/227.png ../../build/png/227-skarmory.png 2>/dev/null
mv ../../build/txt/227.txt ../../build/txt/227-skarmory.txt 2>/dev/null
mv ../../build/html/228.html ../../build/html/228-houndour.html 2>/dev/null
mv ../../build/png/228.png ../../build/png/228-houndour.png 2>/dev/null
mv ../../build/txt/228.txt ../../build/txt/228-houndour.txt 2>/dev/null
mv ../../build/html/229.html ../../build/html/229-houndoom.html 2>/dev/null
mv ../../build/png/229.png ../../build/png/229-houndoom.png 2>/dev/null
mv ../../build/txt/229.txt ../../build/txt/229-houndoom.txt 2>/dev/null
mv ../../build/html/230.html ../../build/html/230-kingdra.html 2>/dev/null
mv ../../build/png/230.png ../../build/png/230-kingdra.png 2>/dev/null
mv ../../build/txt/230.txt ../../build/txt/230-kingdra.txt 2>/dev/null
mv ../../build/html/231.html ../../build/html/231-phanpy.html 2>/dev/null
mv ../../build/png/231.png ../../build/png/231-phanpy.png 2>/dev/null
mv ../../build/txt/231.txt ../../build/txt/231-phanpy.txt 2>/dev/null
mv ../../build/html/232.html ../../build/html/232-donphan.html 2>/dev/null
mv ../../build/png/232.png ../../build/png/232-donphan.png 2>/dev/null
mv ../../build/txt/232.txt ../../build/txt/232-donphan.txt 2>/dev/null
mv ../../build/html/233.html ../../build/html/233-porygon2.html 2>/dev/null
mv ../../build/png/233.png ../../build/png/233-porygon2.png 2>/dev/null
mv ../../build/txt/233.txt ../../build/txt/233-porygon2.txt 2>/dev/null
mv ../../build/html/234.html ../../build/html/234-stantler.html 2>/dev/null
mv ../../build/png/234.png ../../build/png/234-stantler.png 2>/dev/null
mv ../../build/txt/234.txt ../../build/txt/234-stantler.txt 2>/dev/null
mv ../../build/html/235.html ../../build/html/235-smeargle.html 2>/dev/null
mv ../../build/png/235.png ../../build/png/235-smeargle.png 2>/dev/null
mv ../../build/txt/235.txt ../../build/txt/235-smeargle.txt 2>/dev/null
mv ../../build/html/236.html ../../build/html/236-tyrogue.html 2>/dev/null
mv ../../build/png/236.png ../../build/png/236-tyrogue.png 2>/dev/null
mv ../../build/txt/236.txt ../../build/txt/236-tyrogue.txt 2>/dev/null
mv ../../build/html/237.html ../../build/html/237-hitmontop.html 2>/dev/null
mv ../../build/png/237.png ../../build/png/237-hitmontop.png 2>/dev/null
mv ../../build/txt/237.txt ../../build/txt/237-hitmontop.txt 2>/dev/null
mv ../../build/html/238.html ../../build/html/238-smoochum.html 2>/dev/null
mv ../../build/png/238.png ../../build/png/238-smoochum.png 2>/dev/null
mv ../../build/txt/238.txt ../../build/txt/238-smoochum.txt 2>/dev/null
mv ../../build/html/239.html ../../build/html/239-elekid.html 2>/dev/null
mv ../../build/png/239.png ../../build/png/239-elekid.png 2>/dev/null
mv ../../build/txt/239.txt ../../build/txt/239-elekid.txt 2>/dev/null
mv ../../build/html/240.html ../../build/html/240-magby.html 2>/dev/null
mv ../../build/png/240.png ../../build/png/240-magby.png 2>/dev/null
mv ../../build/txt/240.txt ../../build/txt/240-magby.txt 2>/dev/null
mv ../../build/html/241.html ../../build/html/241-miltank.html 2>/dev/null
mv ../../build/png/241.png ../../build/png/241-miltank.png 2>/dev/null
mv ../../build/txt/241.txt ../../build/txt/241-miltank.txt 2>/dev/null
mv ../../build/html/242.html ../../build/html/242-blissey.html 2>/dev/null
mv ../../build/png/242.png ../../build/png/242-blissey.png 2>/dev/null
mv ../../build/txt/242.txt ../../build/txt/242-blissey.txt 2>/dev/null
mv ../../build/html/243.html ../../build/html/243-raikou.html 2>/dev/null
mv ../../build/png/243.png ../../build/png/243-raikou.png 2>/dev/null
mv ../../build/txt/243.txt ../../build/txt/243-raikou.txt 2>/dev/null
mv ../../build/html/244.html ../../build/html/244-entei.html 2>/dev/null
mv ../../build/png/244.png ../../build/png/244-entei.png 2>/dev/null
mv ../../build/txt/244.txt ../../build/txt/244-entei.txt 2>/dev/null
mv ../../build/html/245.html ../../build/html/245-suicune.html 2>/dev/null
mv ../../build/png/245.png ../../build/png/245-suicune.png 2>/dev/null
mv ../../build/txt/245.txt ../../build/txt/245-suicune.txt 2>/dev/null
mv ../../build/html/246.html ../../build/html/246-larvitar.html 2>/dev/null
mv ../../build/png/246.png ../../build/png/246-larvitar.png 2>/dev/null
mv ../../build/txt/246.txt ../../build/txt/246-larvitar.txt 2>/dev/null
mv ../../build/html/247.html ../../build/html/247-pupitar.html 2>/dev/null
mv ../../build/png/247.png ../../build/png/247-pupitar.png 2>/dev/null
mv ../../build/txt/247.txt ../../build/txt/247-pupitar.txt 2>/dev/null
mv ../../build/html/248.html ../../build/html/248-tyranitar.html 2>/dev/null
mv ../../build/png/248.png ../../build/png/248-tyranitar.png 2>/dev/null
mv ../../build/txt/248.txt ../../build/txt/248-tyranitar.txt 2>/dev/null
mv ../../build/html/249.html ../../build/html/249-lugia.html 2>/dev/null
mv ../../build/png/249.png ../../build/png/249-lugia.png 2>/dev/null
mv ../../build/txt/249.txt ../../build/txt/249-lugia.txt 2>/dev/null
mv ../../build/html/250.html ../../build/html/250-ho-oh.html 2>/dev/null
mv ../../build/png/250.png ../../build/png/250-ho-oh.png 2>/dev/null
mv ../../build/txt/250.txt ../../build/png/250-ho-oh.txt 2>/dev/null
mv ../../build/html/251.html ../../build/html/251-celebi.html 2>/dev/null
mv ../../build/png/251.png ../../build/png/251-celebi.png 2>/dev/null
mv ../../build/txt/251.txt ../../build/txt/251-celebi.txt 2>/dev/null
